"use strict";
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (Object.hasOwnProperty.call(mod, k)) result[k] = mod[k];
    result["default"] = mod;
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
// THIS FILE IS AUTOGENERATED. DO NOT EDIT
/* eslint-disable */
/* tslint:disable */
const server = __importStar(require("./server"));
exports.server = server;
const serverApi = __importStar(require("./serverApi"));
exports.serverApi = serverApi;
const serverUi = __importStar(require("./serverUi"));
exports.serverUi = serverUi;
//# sourceMappingURL=index.js.map